M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-26T18:07:37+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-26T18:07:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X131.56Y-83.73
X131.56Y-89.51
M30
